package com.datagami.rentaxis.domain.entity.enums;

public enum TransactionNature {
    RENT_PAYMENT_CLEARED,
    SECURITY_DEPOSIT_RECEIVED,
    SECURITY_DEPOSIT_REFUNDED,
    CHEQUE_BOUNCED,
    SALARY_PAYMENT,
    VENDOR_PAYMENT,
    VENDOR_INVOICE_RECEIVED,
    MAINTENANCE_EXPENSE,
    UTILITY_PAYMENT
}
