// Tutorial 18. Default role for scenes that do not name one: tenantAdmin.
import { routeScene } from '../lib/scenes.mjs';

const scenes = [
  routeScene('/en/dashboard/finance/transactions', 'Financial transactions', 'Review journal activity generated by rent, deposits, charges, expenses, and corrections.'),
  routeScene('/en/dashboard/finance/transactions', 'Transaction scope', 'Use dates, account filters, property scope, and description search to find an entry.', async (page) => {
    await page.getByRole('button', { name: 'Filter', exact: true }).click();
    await page.locator('select').first().waitFor({ state: 'visible', timeout: 10000 });
  }),
  routeScene('/en/dashboard/finance/reports', 'Reconcile through reports', 'Move from individual postings to a generated profit-and-loss report.', async (page) => {
    await page.getByRole('button', { name: 'Generate Report', exact: true }).click();
    await page.getByText('Total Income', { exact: true }).first().waitFor({ state: 'visible', timeout: 15000 });
  }),
];

export default { role: 'tenantAdmin', scenes };
