name: manager
description: "RentAxis Manager App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rentaxis_core:
    path: ../../packages/rentaxis_core
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  permission_handler: ^11.3.1
  open_filex: ^4.5.0
  path_provider: ^2.1.5
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
