spring:
  application:
    name: RentAxis
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rentaxis}
    username: ${SPRING_DATASOURCE_USERNAME:rentaxis}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

rentaxis:
  contracts:
    storage-path: ./data/contracts
  encryption:
    key: ${RENTAXIS_ENCRYPTION_KEY:}
